// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("NauckIT.PostgreSQLProvider")]
[assembly: AssemblyProductAttribute("NauckIT.PostgreSQLProvider")]
[assembly: AssemblyDescriptionAttribute("A ASP.NET 2.0+ Membership, Role, Profile and Session-State Store Provider")]
[assembly: AssemblyVersionAttribute("2.1")]
[assembly: AssemblyFileVersionAttribute("2.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.1";
    }
}
