// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Example")]
[assembly: AssemblyProductAttribute("NauckIT.PostgreSQLProvider")]
[assembly: AssemblyDescriptionAttribute("A ASP.NET 2.0+ Membership, Role, Profile and Session-State Store Provider")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
